
package gui;

/**
 *
 * @author DaTorres
 */
public class FormSobreAplicativo extends javax.swing.JInternalFrame {

    private static FormSobreAplicativo instance = null;

    public static FormSobreAplicativo getInstance() {

        if (instance == null) {

            instance = new FormSobreAplicativo();

        }

        return instance;
    }

    public static boolean isOpen() {

        return instance != null;
    }
    
    public FormSobreAplicativo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblNomeSistema = new javax.swing.JLabel();
        lblInformacaoSubTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblLinha6 = new javax.swing.JLabel();
        lblLinha2 = new javax.swing.JLabel();
        lblLinha3 = new javax.swing.JLabel();
        lblLinha4 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblNomeSistema.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNomeSistema.setForeground(new java.awt.Color(0, 102, 255));
        lblNomeSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeSistema.setText("Sub-Sistema SisSegHospeda");

        lblInformacaoSubTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblInformacaoSubTitulo.setForeground(new java.awt.Color(0, 102, 255));
        lblInformacaoSubTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInformacaoSubTitulo.setText("Sistema Gerador de Carteiras da Farmácia Básica");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInformacaoSubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblNomeSistema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInformacaoSubTitulo)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        lblLinha6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinha6.setForeground(new java.awt.Color(255, 255, 255));
        lblLinha6.setText("O SisSegHospeda é um sistema que tem por finalidade reconhecer e");
        jPanel2.add(lblLinha6);
        lblLinha6.setBounds(10, 50, 420, 17);

        lblLinha2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinha2.setForeground(new java.awt.Color(255, 255, 255));
        lblLinha2.setText(" cadastrar informações referente a alguns dispositivos  encontrados");
        jPanel2.add(lblLinha2);
        lblLinha2.setBounds(10, 80, 420, 17);

        lblLinha3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinha3.setForeground(new java.awt.Color(255, 255, 255));
        lblLinha3.setText("na Maquina onde roda a aplicação em questão.");
        jPanel2.add(lblLinha3);
        lblLinha3.setBounds(10, 110, 300, 17);

        lblLinha4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLinha4.setForeground(new java.awt.Color(255, 255, 255));
        lblLinha4.setText("Desenvolvedor: Analista de Sistemas Tonis Alberto Torres Ferreira");
        jPanel2.add(lblLinha4);
        lblLinha4.setBounds(10, 140, 410, 17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        setBounds(600, 150, 470, 320);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
       instance=null;
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblInformacaoSubTitulo;
    private javax.swing.JLabel lblLinha2;
    private javax.swing.JLabel lblLinha3;
    private javax.swing.JLabel lblLinha4;
    private javax.swing.JLabel lblLinha6;
    private javax.swing.JLabel lblNomeSistema;
    // End of variables declaration//GEN-END:variables
}
